### PR TITLE
Models

### PR DESCRIPTION
**Pull request by Erikmoto**
Seel line added

### CODE REVIEW

**Comment by Thutmose** [comment]
Very nice models, thanks.

Next time, can you try to avoid including the build related xml files?

**Comment by Erikmoto** [comment]
Sorry, I was a little lost with Github

**Comment by Thutmose** [comment]
no problem, those models also made me realize that tabula's animation system has some flaws, so I am writing a proper converter from tabula to obj, so I can do the rigging for animation in blender for them.

**Comment by Erikmoto** [comment]
Ok.
I'm thinking on doing Sandshrew line next, so maybe I'll give Blender a try if I manage how to work with it.
Anyway, this mod is really incredible and each time I see it gets better and better. Nice job.

**Comment by Thutmose** [comment]
Ok, I made a jar that can convert from tabula models to a format that blender can import, so you can make the models in whichever is easier for you, tabula is probably easier to make the models in than blender.

**Comment by Erikmoto** [comment]
Nice.

**Pull request merged**
